<!DOCTYPE html>
<html>
<head>
<title>Candidate Page</title>
<link rel="stylesheet" type="text/css" href="css/candidate.css">
</head>
<body>
<div class="heading">
<h1>Candidates</h1>
</div>
<div class="container">
<img src="https://img.theweek.in/content/dam/week/news/india/images/2018/8/30/shiv-sena-logo-week.jpg" width="150" height="150"/>
<p align="center">Shiv Sena,is an Indian far-right regional political party.Its ideology is based on pro-Marathi ideology and Hindu nationalism (Hindutva),founded on 19 June 1966 by political cartoonist Bal Thackeray.The party originally emerged from a movement in Mumbai demanding preferential treatment for Maharashtrians over migrants to the city.It is currently headed by Thackeray's son,Uddhav Thackeray.Members of Shiv Sena are referred to as Shivsainiks.Although the party's primary base is still in Maharashtra,it has tried to expand to a pan-Indian base.In the 1970s,it gradually moved from advocating a pro-Marathi ideology to one supporting a broader Hindu nationalist agenda,as it aligned itself with the Bharatiya Janata Party.The party started taking part in Mumbai (BMC) Municipal elections since its inception.In 1989,it entered into an alliance with the BJP for Lok Sabha as well as Maharashtra assembly elections,the latter of which was temporarily broken in October 2014 Assembly elections.</p>
<img src="https://www.logolynx.com/images/logolynx/5f/5f04d28587d594758c4c88cc513f8106.jpeg" width="150" height="150"/>
<p align="center">The Maharashtra Navnirman Sena (मराठी: महाराष्ट्र नवनिर्माण सेना) is an nationalist far-right Indian political party based in the state of Maharashtra and operates on the motto of "Sons of the Soil". It was founded on 9 March 2006 in Mumbai by Raj Thackeray after he left the Shiv Sena party due to differences with his paternal cousin Uddhav Thackeray and to his sidelining by the Shiv Sena in major decisions like distribution of election tickets.MNS won 13 assembly seats (out of 288) in the 2009 assembly elections,which was the first Maharashtra Legislative Assembly election that the party contested.In the most recent elections of Maharashtra Legislative Assembly 2014,MNS was reduced to a single seat.</p>
<img src="http://bichhu.com/wp-content/uploads/2018/05/BJP-Logo-BJP.jpg" width="150" height="150"/><br><br>
<p align="center">The Bharatiya Janata Party is one of the two major political parties in India,along with the Indian National Congress.As of 2018,it is the country's largest political party in terms of representation in the national parliament and state assemblies,and it is the world's largest party in terms of primary membership.BJP is a right-wing party,and its policy has historically reflected Hindu-nationalist positions.It has close ideological and organisational links to the Rashtriya Swayamsevak Sangh.The BJP's origin lies in the Bharatiya Jana Sangh,formed in 1951 by Syama Prasad Mukherjee.After the State of Emergency in 1977,the Jana Sangh merged with several other parties to form the Janata Party;it defeated the incumbent Congress party in the 1977 general election.</p>
<img src="https://img.dainiksaveratimes.com/Uploads/img/2016/11/12/2812112016030459.png" width="150" height="150"/><br><br>
<p align="center">The Indian National Congress(INC, often called Congress Party) is a broadly based political party in India.Founded in 1885,it was the first modern nationalist movement to emerge in the British Empire in Asia and Africa.From the late 19th century,and especially after 1920,under the leadership of Mahatma Gandhi,Congress became the principal leader of the Indian independence movement.Congress led India to independence from Great Britain,and powerfully influenced other anti-colonial nationalist movements in the British Empire.Congress like all other parties registered in India,is a secular[citation needed] party (India is a secular country since 1976 after Forty-second Amendment of the Constitution of India) whose social liberal platform is generally considered to be on the centre-left of Indian politics.Congress' social policy is based upon the Gandhian principle of Sarvodaya—the lifting up of all sections of society—which involves the improvement of the lives of economically underprivileged and socially marginalised people.The party primarily endorses social liberalism—seeking to balance individual liberty and social justice,and secularism—asserting the right to be free from religious rule and teachings.</p>
<img src="https://cdn.dnaindia.com/sites/default/files/styles/full/public/2018/09/30/737639-aap-logo.jpg" width="150" height="150"/><br><br>
<p align="center">Aam Aadmi Party is an Indian political party,formally launched on 26 November 2012,and is currently the ruling party of the National Capital Territory of Delhi.It came into existence following differences between the activists Arvind Kejriwal and Anna Hazare regarding whether or not to politicise the popular India Against Corruption movement that had been demanding a Jan Lokpal Bill since 2011.Hazare preferred that the movement should remain politically unaligned while Kejriwal felt the failure of the agitation route necessitated a direct political involvement.The party made its electoral debut in the 2013 Delhi Legislative Assembly election,where it emerged as the second-largest party,winning 28 of the 70 seats.With no party obtaining an overall majority,the AAP formed a minority government with conditional support from the Indian National Congress.A significant part of its agenda was to quickly introduce the Jan Lokpal bill in the National Capital Territory of Delhi.When it became clear after the election that the other major parties would not support this bill,the AAP government resigned.It had been in power for 49 days.</p>
</div>
</body>
</html>
